# Generated by Django 3.0.5 on 2020-08-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='token',
        ),
    ]
