# Generated by Django 3.0.5 on 2020-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
