# Generated by Django 3.0.5 on 2020-07-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200726_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donator',
        ),
        migrations.CreateModel(
            name='DataGive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_data', to='webapp.Donator')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_data', to='webapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='donator',
            name='projects',
            field=models.ManyToManyField(through='webapp.DataGive', to='webapp.Project'),
        ),
    ]
