# Generated by Django 3.0.5 on 2020-07-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200727_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datagive',
            old_name='Donator',
            new_name='donator',
        ),
        migrations.RenameField(
            model_name='datagive',
            old_name='Project',
            new_name='project',
        ),
    ]
