# Generated by Django 3.0.5 on 2020-07-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200728_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='donator',
            field=models.ManyToManyField(blank=True, to='webapp.Donator'),
        ),
        migrations.DeleteModel(
            name='DataGive',
        ),
    ]
