# Generated by Django 3.0.5 on 2020-07-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200729_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_data', to='webapp.Donator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_data', to='webapp.Project')),
            ],
        ),
    ]
